#!/bin/sh

currentDir=$( echo ${PWD##*/} )

red='\033[0;31m'
blue='\033[0;34m'
green='\033[0;32m'
reset='\033[0m'

echo "SASS or LESS? (1 or SASS, 2 for LESS)"
read csscompiler

if [ $currentDir != 'LeadPagesBuildSystem' ]; then


	# New Template. Switch branch to yeoman to copy the skeleton folders and files
	if [ ! -d "leadpages-template" ]; then
		echo "${green}No leadpages-template folder found. Getting a skeleton copy.${reset}"

		mkdir tmp && \
		git checkout yeoman && \
		cp -r ./leadpages-template ./tmp/leadpages-template && \
		git co master && \
		cp -r ./tmp/leadpages-template ./leadpages-template && \
		rm -rf ./tmp
	fi

	if [ $csscompiler -eq 1]; then
		rm -rf less && rm gulp/tasks/less.js
	else
		rm -rf sass && rm gulp/tasks/sass.js
	fi

	echo "${blue}Installing Build System...${reset}"
	npm install
	rm -rf .git install readme && \
	echo \n\n"node_modules" >> .gitignore && \
	echo \n\n".DS_Store" >> .gitignore

	if [ ! -d ".git" ]; then
		git init && git add . && git status
	fi
else
	echo "${blue}Installing Build System...${reset}"
	rm -rf .git readme.md install && \
	cp -r * ../
	cd ..
	rm -rf LeadPagesBuildSystem

	echo "${red}Please${reset} ${green}cd ..${reset} ${red}and run${reset} ${green}npm install${reset}"
fi

echo "${blue}Done! Happy coding!${reset}"